version: '2'
services:
  valkey:
    image: valkey/valkey:alpine3.20
  postgres:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: rest_api_user
      POSTGRES_PASSWORD: rest_api_pass
      POSTGRES_DB: rest_api_db
  api:
    build:
      context: .
      dockerfile: debian.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - valkey
    environment:
      DATABASE_URL: postgres://rest_api_user:rest_api_pass@postgres/rest_api_db
      REDIS_URL: http://redis
    # network_mode: host
#    entrypoint: [ "/usr/local/bin/wait4x", "postgresql", "postgres:5432", "--",
#      #                  "${DATABASE_URL}"
#                  "/usr/local/bin/wait4x", "redis", "redis:6379", "&&",
#      #                  "${REDIS_URL}"
#                  "/app/bin/serve-actix-diesel-auth-scaffold" ]
